Algoritmo "Média"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Marcos
// Descrição   : Programa para calcular média de alunos
// Autor(a)    : Eduardo araújo dos santos
// Data atual  : 25/05/2022

VAR nota1, nota2, nota3: REAL;


Inicio

escreva("Digite a 1ª nota:")
leia(nota1)

escreva("Digite a 2ª nota:")
leia(nota2)

escreva("Digite a 3ª nota:")
leia(nota3)

escreva("Média obtida: ", ((nota1+nota2+nota3)/3))



Fimalgoritmo