Algoritmo "tipo de dados "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Marcos
// Descrição   : Programa para calcular média de alunos
// Autor(a)    : Eduardo araújo dos santos
// Data atual  : 25/05/2022

VAR

Total, Maior, Menor : INTEIRO;
Nota, Media, altura : REAL;
Resposta : LOGICO;

INICIO

Maior <- 50;
Menor <- 40;
Total <- (Maior-Menor);
Resposta <- Verdadeiro;

escreva(Maior, " - ", Menor, " = ", Total)
escreva(" O Resultado é:", Resposta)


Fimalgoritmo