Algoritmo "soma_100primeiros"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Marcos
// Descrição   : Programa para pegar os 100 primeiros numeros inteiro e soma-los
// Autor(a)    : Eduardo Araújo dos Santos
// Data atual  : 26/05/2022

Var

soma,num: inteiro

Inicio

num<-1
 repita
soma<-soma+num
num<-num+1
ate num=100

escreval ("o total da soma dos 100 numeros inteiros é:",soma)


Fimalgoritmo